---
title: "DATA 609 HW Week 14 & 15"
author: "Ahsanul Choudhury"
date: "May 12, 2018"
output:
    pdf_document:
    toc: yes
    toc_depth: 2
   
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newpage

#Week 14

##Page B-13: #4

Discuss how you might go about validating the nuclear arms race model. What data would you collect? Is it possible to obtain the data?

***Solution***

To validate the model, we may use historical data of previous arms races between powerful nations of modern era. However, these data may need to be aggregated as technological advancement in destruction power and delivery methods such as nuclear missile carrying submarines means nations can inflict maximum damage to their enemies with fewer missiles and positioning them strategically. It is impossible to destroy the friendly missile force with massive first attack completely when they can be scattered all over the world in submarines which can initiate counter attack independently and can cause major damage with the technologically advanced missile they carry.

It will be a tall order to collect such complete historical data as these data may deemed top secret and closely guarded.


## Page B-24: #1
Verify the result that the marginal revenue of the (q+1)st unit equals the price of that unit minus the loss in revenue on previous units resulting from price reduction.

***Solution***

Marginal revenue is the additional revenue generated from the sale of an additional unit of output. In other words , it's the change in total revenue from the sale of one more unit of a good. In algebraic terms, marginal revenue is the net addition to the total revenue by selling n units of a commodity instead of n - 1.

Let

$q$ = output

$p$ = average price or revenue per unit

$n$ = any given number

$TR_n$ = Total revenue of n units

$TR_{n-1}$ = Total revenue from (n-1) unit

$p_{n}$ = Price of (q + 1)st unit



Total revenue,

$$TR = p\times q$$
$$TR_n = TR_{n-1} + p_{n}$$
Therefore,

$$p_{n} = TR_n - TR_{n-1}$$
 

$$MR = \frac{\Delta TR}{\Delta q}$$

$$MR_n = TR_n - TR_{n-1} = p_n$$

So we can see, the marginal revenue of the (q+1)st unit equals the price of that unit minus the loss in revenue on previous units resulting from price reduction



\newpage

#Week 15

A company is assembling a team to carry out a series of operations. There are four members of the team: A, B, C and D, and four operations to be carried out. Each team member can carry out exactly one operation. All four operations must be carried out successfully for the overall project to succeed, however the probability of a particular team member succeeding in a particular operation varies, as shown in the table below. For example, if the team members were assigned to operations in the order ABCD, then the overall probability of successful completion of the project is (0.9)(0.6)(0.85)(0.7) = 0.3213. If there is any
possible way that the team can be arranged such that the overall probability of success exceeds 45%, then the manager will approve the project. Will the manager approve the project? If yes, what is the arrangement of the team that gives the highest probability of success?


***Solution***

HW Solution already provided by Dr. Wang.

Solution link:

http://optlab-server.sce.carleton.ca/POAnimations2007/BranchAndBound.html